# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 17:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('monum_type', models.CharField(max_length=25)),
                ('civilization', models.CharField(max_length=25)),
                ('approx_end_date', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000)])),
                ('arch_style', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('country', models.CharField(default=b'Spain', max_length=25)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)])),
                ('exp_points', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('options', jsonfield.fields.JSONField()),
                ('solution', models.CharField(max_length=100)),
                ('hint', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('?',),
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[(b'S', b'Small'), (b'M', b'Medium'), (b'L', b'Large')], max_length=1)),
                ('difficulty', models.CharField(choices=[(b'E', b'Easy'), (b'M', b'Medium'), (b'H', b'Hard')], max_length=1)),
                ('max_hints', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travial_web_app.Monument')),
                ('questions', models.ManyToManyField(to='travial_web_app.Question')),
            ],
            options={
                'ordering': ('monument',),
            },
        ),
    ]
