# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travial_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'user_avatars/'),
        ),
        migrations.AddField(
            model_name='trivia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'trivia_images/'),
        ),
    ]
