 version: '2'
 services:
   db:
     image: postgres
   web:
     build: .
     command: gunicorn -b 0.0.0.0:8000 travial_web.wsgi --log-file  -
     volumes:
       - .:/Travial-Web
     ports:
       - "8000:8000"
     depends_on:
       - db
